#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          on
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85
yabai -m config window_border                off
yabai -m config window_border_width          02
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  04
yabai -m config bottom_padding               04
yabai -m config left_padding                 06
yabai -m config right_padding                06
yabai -m config window_gap                   05

# Rules
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Docker$" manage=off
yabai -m rule --add app="^Arc$" title="^Space.*$" manage=off layer=below
yabai -m rule --add app="^Arc$" title="^$" manage=off layer=below
yabai -m rule --add app="^zoom\.us$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" title="^Connect to Server$" manage=off
yabai -m rule --add app="^Finder$" title="^Connecting to Server$" manage=off
yabai -m rule --add app="^Finder$" title="^.* Info$" manage=off
yabai -m rule --add app="^Finder$" title="^Copy$" manage=off

echo "yabai configuration loaded.."
